package service

import (
	"kasir-api/data"
	"kasir-api/entity"
	"strings"
)

// CategoryService handles business logic for category operations
type CategoryService struct {
	storage data.CategoryStorage
}

// NewCategoryService creates a new instance of CategoryService
func NewCategoryService(storage data.CategoryStorage) *CategoryService {
	return &CategoryService{
		storage: storage,
	}
}

// GetAll retrieves all categories
func (s *CategoryService) GetAll() ([]*entity.Category, error) {
	return s.storage.GetAll()
}

// GetByID retrieves a category by ID
func (s *CategoryService) GetByID(id int) (*entity.Category, error) {
	if id <= 0 {
		return nil, entity.ErrIDRequired
	}
	return s.storage.GetByID(id)
}

// Create creates a new category with validation
func (s *CategoryService) Create(category *entity.Category) (*entity.Category, error) {
	// Validate input
	if err := s.validateCategory(category); err != nil {
		return nil, err
	}

	// ID will be auto-generated by storage
	// Save to storage
	if err := s.storage.Create(category); err != nil {
		return nil, err
	}

	return category, nil
}

// Update updates an existing category with validation
func (s *CategoryService) Update(id int, category *entity.Category) (*entity.Category, error) {
	if id <= 0 {
		return nil, entity.ErrIDRequired
	}

	// Validate input
	if err := s.validateCategory(category); err != nil {
		return nil, err
	}

	// Set ID from path parameter
	category.ID = id

	// Update in storage
	if err := s.storage.Update(category); err != nil {
		return nil, err
	}

	return category, nil
}

// Delete removes a category by ID
func (s *CategoryService) Delete(id int) error {
	if id <= 0 {
		return entity.ErrIDRequired
	}
	return s.storage.Delete(id)
}

// validateCategory validates category fields
func (s *CategoryService) validateCategory(category *entity.Category) error {
	if strings.TrimSpace(category.Name) == "" {
		return entity.ErrNameRequired
	}
	return nil
}
