package service

import (
	"kasir-api/data"
	"kasir-api/entity"
	"strings"
)

// ProductService handles business logic for product operations
type ProductService struct {
	storage data.ProductStorage
}

// NewProductService creates a new instance of ProductService
func NewProductService(storage data.ProductStorage) *ProductService {
	return &ProductService{
		storage: storage,
	}
}

// GetAll retrieves all products
func (s *ProductService) GetAll() ([]*entity.Product, error) {
	return s.storage.GetAll()
}

// GetByID retrieves a product by ID
func (s *ProductService) GetByID(id int) (*entity.Product, error) {
	if id <= 0 {
		return nil, entity.ErrIDRequired
	}
	return s.storage.GetByID(id)
}

// Create creates a new product with validation
func (s *ProductService) Create(product *entity.Product) (*entity.Product, error) {
	// Validate input
	if err := s.validateProduct(product); err != nil {
		return nil, err
	}

	// ID will be auto-generated by storage
	// Save to storage
	if err := s.storage.Create(product); err != nil {
		return nil, err
	}

	return product, nil
}

// Update updates an existing product with validation
func (s *ProductService) Update(id int, product *entity.Product) (*entity.Product, error) {
	if id <= 0 {
		return nil, entity.ErrIDRequired
	}

	// Validate input
	if err := s.validateProduct(product); err != nil {
		return nil, err
	}

	// Set ID from path parameter
	product.ID = id

	// Update in storage
	if err := s.storage.Update(product); err != nil {
		return nil, err
	}

	return product, nil
}

// Delete removes a product by ID
func (s *ProductService) Delete(id int) error {
	if id <= 0 {
		return entity.ErrIDRequired
	}
	return s.storage.Delete(id)
}

// validateProduct validates product fields
func (s *ProductService) validateProduct(product *entity.Product) error {
	if strings.TrimSpace(product.Name) == "" {
		return entity.ErrNameRequired
	}
	if product.Price <= 0 {
		return entity.ErrPriceInvalid
	}
	if product.Stock < 0 {
		return entity.ErrStockInvalid
	}
	return nil
}
